# Pytorch

In [3]:
# 토치가 설치가 잘 됐는지 확인하는 법 Fals가 나오면 문제가 있는 것임.
import torch

torch.cuda.is_available()

True

In [4]:
# 토치 버전확인하는 법
torch.__version__

'2.8.0+cu126'

In [5]:
torch.tensor(5)  # 숫자 5를 '텐서(Tensor)'라는 파이토치 자료형으로 바꿈

tensor(5)

In [6]:
torch.tensor([1,2,3])  # 리스트 → PyTorch 텐서로 변환 (딥러닝 연산용)

tensor([1, 2, 3])

In [7]:
torch.tensor([[1,2,3],[4,5,6]])  # 2D 데이터 → 텐서 변환 (shape: 2x3, 행렬 형태)


tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
data = [1,2,3,4,5]   # 1차원 리스트
torch.tensor(data)   # 리스트 → 1D 텐서 (shape: 5,)

tensor([1, 2, 3, 4, 5])

In [9]:
import numpy as np

data = np.array([1,2,3,4,5])   # 1차원 NumPy 배열 (shape: 5,)
torch.tensor(data)   # NumPy 배열 → 1D 텐서 (shape: 5,)

tensor([1, 2, 3, 4, 5])

In [10]:
torch.ones(3)   # 원소 3개, 모두 1.0인 1D 텐서 생성

tensor([1., 1., 1.])

In [11]:
torch.ones(3,5)  # 3행 5열, 모든 값이 1.0인 2D 텐서 생성

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [12]:
# 이미지 =  1: 흰색    0: 검정색

torch.ones(512,512)  # 512행 512열, 모든 값이 1.0인 대형 2D 텐서 생성


tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [13]:
# 색상: 검정색
torch.zeros(512,512)  # 512행 512열, 모든 값이 1.0인 대형 2D 텐서 생성

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [14]:
# 단위행렬
torch.eye(5) # 5x5 크기, 대각선만 1이고 나머지는 0인 단위 행렬 생성

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
# 시작이 1 끝이 9
torch.arange(1,10) # 1부터 9까지 연속된 숫자(1D 텐서) 생성

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# 시작이 1 끝이 9 간격은 2
torch.arange(1,10,2) # 1부터 9까지 2씩 증가하는 1D 텐서 생성

tensor([1, 3, 5, 7, 9])

In [ ]:
# 3열 3행 3줄 만들어라
data = torch.rand(3,3,3) # 3x3x3 크기, 0~1 사이 난수로 채워진 3D 텐서 생성
data

tensor([[[0.5387, 0.8932, 0.6182],
         [0.6183, 0.6576, 0.0949],
         [0.8510, 0.9923, 0.6272]],

        [[0.8200, 0.5368, 0.9764],
         [0.5019, 0.5362, 0.3209],
         [0.9424, 0.6617, 0.4123]],

        [[0.8307, 0.7699, 0.8107],
         [0.2042, 0.6241, 0.0273],
         [0.7602, 0.3549, 0.9588]]])

In [18]:
# 차원의 수를 확인할 수 있는 함수
data.dim()

3

In [19]:
# 3차원을 2차원으로 만들기
data.view(9,3) # 9행 3열 짜리고 만들기

tensor([[0.5387, 0.8932, 0.6182],
        [0.6183, 0.6576, 0.0949],
        [0.8510, 0.9923, 0.6272],
        [0.8200, 0.5368, 0.9764],
        [0.5019, 0.5362, 0.3209],
        [0.9424, 0.6617, 0.4123],
        [0.8307, 0.7699, 0.8107],
        [0.2042, 0.6241, 0.0273],
        [0.7602, 0.3549, 0.9588]])

In [20]:
data.view(27)

tensor([0.5387, 0.8932, 0.6182, 0.6183, 0.6576, 0.0949, 0.8510, 0.9923, 0.6272,
        0.8200, 0.5368, 0.9764, 0.5019, 0.5362, 0.3209, 0.9424, 0.6617, 0.4123,
        0.8307, 0.7699, 0.8107, 0.2042, 0.6241, 0.0273, 0.7602, 0.3549, 0.9588])

In [21]:
data.view(3,9)

tensor([[0.5387, 0.8932, 0.6182, 0.6183, 0.6576, 0.0949, 0.8510, 0.9923, 0.6272],
        [0.8200, 0.5368, 0.9764, 0.5019, 0.5362, 0.3209, 0.9424, 0.6617, 0.4123],
        [0.8307, 0.7699, 0.8107, 0.2042, 0.6241, 0.0273, 0.7602, 0.3549, 0.9588]])

In [22]:
data.view(3,-1)

tensor([[0.5387, 0.8932, 0.6182, 0.6183, 0.6576, 0.0949, 0.8510, 0.9923, 0.6272],
        [0.8200, 0.5368, 0.9764, 0.5019, 0.5362, 0.3209, 0.9424, 0.6617, 0.4123],
        [0.8307, 0.7699, 0.8107, 0.2042, 0.6241, 0.0273, 0.7602, 0.3549, 0.9588]])

In [23]:
data.view(9,-1)

tensor([[0.5387, 0.8932, 0.6182],
        [0.6183, 0.6576, 0.0949],
        [0.8510, 0.9923, 0.6272],
        [0.8200, 0.5368, 0.9764],
        [0.5019, 0.5362, 0.3209],
        [0.9424, 0.6617, 0.4123],
        [0.8307, 0.7699, 0.8107],
        [0.2042, 0.6241, 0.0273],
        [0.7602, 0.3549, 0.9588]])

In [24]:
data.view(-1)

tensor([0.5387, 0.8932, 0.6182, 0.6183, 0.6576, 0.0949, 0.8510, 0.9923, 0.6272,
        0.8200, 0.5368, 0.9764, 0.5019, 0.5362, 0.3209, 0.9424, 0.6617, 0.4123,
        0.8307, 0.7699, 0.8107, 0.2042, 0.6241, 0.0273, 0.7602, 0.3549, 0.9588])

In [25]:
data.shape

torch.Size([3, 3, 3])

In [26]:
data.dim()

3

In [27]:
data.dtype

torch.float32

In [28]:
# 쿠다를 쓸 수 있는지 확인
torch.cuda.is_available()

True

In [29]:
# cuda GPU 장치 개수
torch.cuda.device_count()

1

In [30]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4070 Laptop GPU'

In [31]:
device = torch.device("cuda:1")
device

device(type='cuda', index=1)

In [32]:
# 현재 데이터는 CPU 메모리에 있다.
data = torch.tensor([1,2,3])
data

tensor([1, 2, 3])

In [33]:
# 데이터를 GPU로 옮기는 방법 1
data.to("cuda")

tensor([1, 2, 3], device='cuda:0')

In [34]:
# 데이터를 GPU로 옮기는 방법 2
data1 = torch.tensor([1,2,3]).cuda()
data1

tensor([1, 2, 3], device='cuda:0')

In [35]:
# GPU 메모리에서 CPU 메모리로 바꾸는 방법
data1.to('cpu')

tensor([1, 2, 3])

In [36]:
data

tensor([1, 2, 3])

In [37]:
data1

tensor([1, 2, 3], device='cuda:0')

In [38]:
# CPU 였던 data를 GPU로 바꿔줘서 더하기를 가능하게 했다.
data = data.to("cuda")
data + data1

tensor([2, 4, 6], device='cuda:0')

In [39]:
data + data1

tensor([2, 4, 6], device='cuda:0')

In [40]:
data * data1

tensor([1, 4, 9], device='cuda:0')

In [41]:
data / data1

tensor([1., 1., 1.], device='cuda:0')

In [42]:
data = torch.tensor([[1,2,3],[4,5,6]])
data

tensor([[1, 2, 3],
        [4, 5, 6]])

In [43]:
data.min()

tensor(1)

In [44]:
data.min(dim=0)

torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))

In [45]:
data.min(dim=1)

torch.return_types.min(
values=tensor([1, 4]),
indices=tensor([0, 0]))

In [46]:
data.max()

tensor(6)

In [47]:
data .max(dim=0)

torch.return_types.max(
values=tensor([4, 5, 6]),
indices=tensor([1, 1, 1]))

In [48]:
data .max(dim=1)

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

In [49]:
data

tensor([[1, 2, 3],
        [4, 5, 6]])

In [50]:
data.dtype

torch.int64

In [51]:
# 데이터 타입 바꿔주는 방법
data = data.type(torch.float)
data

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [52]:
data.dtype

torch.float32

In [53]:
data.mean()

tensor(3.5000)

In [54]:
image = torch.rand(3,128,128)
image = image.view(1,3,128,128)
image.dim()

4

- 원래 텐서 shape가 (3, 128, 128)일 때:
    - `unsqueeze(dim=0)` → (1, 3, 128, 128) (맨 앞에 1차원 추가)
    - `unsqueeze(dim=1)` → (3, 1, 128, 128) (두 번째 차원 위치에 1차원 추가)

- `squeeze()` ->  크기가 1인 차원(축)을 제거

- `unsqueeze()` 와 `view(new_shape)`의 차이:
    - `unsqueeze(dim)`:
        - 역할: 특정 위치에 크기 1인 차원 하나 추가
        - 차원 수 변화: 차원 수가 +1 (하나 늘어남)
        - 사용 목적: 배치 차원 추가, 차원 맞춤 등 간단한 차원 추가
        - 제약사항: 없음 (어디든 크기 1 차원 추가 가능)

    - `view(new_shape)`:
        - 역할: 텐서의 전체 차원 형태를 새로운 모양으로 재구성
        - 차원 수 변화: 차원 수는 변할 수 있으나, 요소 개수는 동일해야 함
        - 사용 목적: 텐서를 원하는 모양으로 리쉐이핑 (예: (4,3) → (2,6))
        - 제약사항: 전체 원소 개수는 변하지 않아야 함

In [55]:
image = torch.rand(3,128,128)
image = image.unsqueeze(dim=0) # 새로운 차원을 만들어 준다.
image.shape

torch.Size([1, 3, 128, 128])

In [56]:
image.shape

torch.Size([1, 3, 128, 128])

In [57]:
data = torch.rand(1,128,128)
data = data.squeeze() # 아무 의미없는 특징,차원을 제거
data.shape

torch.Size([128, 128])